//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Catan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string ActionType_Build {
            get {
                return ResourceManager.GetString("ActionType_Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Turn.
        /// </summary>
        internal static string ActionType_EndTurn {
            get {
                return ResourceManager.GetString("ActionType_EndTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string ActionType_PlayDevCard {
            get {
                return ResourceManager.GetString("ActionType_PlayDevCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build City.
        /// </summary>
        internal static string ActionType_RequestCity {
            get {
                return ResourceManager.GetString("ActionType_RequestCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Dev Card.
        /// </summary>
        internal static string ActionType_RequestDevCard {
            get {
                return ResourceManager.GetString("ActionType_RequestDevCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Road.
        /// </summary>
        internal static string ActionType_RequestRoad {
            get {
                return ResourceManager.GetString("ActionType_RequestRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Settlement.
        /// </summary>
        internal static string ActionType_RequestSettlement {
            get {
                return ResourceManager.GetString("ActionType_RequestSettlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade 4:1.
        /// </summary>
        internal static string ActionType_RequestTradeBasic {
            get {
                return ResourceManager.GetString("ActionType_RequestTradeBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Dice.
        /// </summary>
        internal static string ActionType_RollDice {
            get {
                return ResourceManager.GetString("ActionType_RollDice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose something you can afford! Begin building or end turn..
        /// </summary>
        internal static string Build_CannotAfford {
            get {
                return ResourceManager.GetString("Build_CannotAfford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, there are no valid places for you to build that. Begin building or end turn..
        /// </summary>
        internal static string Build_CannotPlace {
            get {
                return ResourceManager.GetString("Build_CannotPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin building or end turn..
        /// </summary>
        internal static string Build_Instruction {
            get {
                return ResourceManager.GetString("Build_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already played a dev card this turn!.
        /// </summary>
        internal static string DevCard_AlreadyPlayed {
            get {
                return ResourceManager.GetString("DevCard_AlreadyPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot play a dev card that you bought this turn!.
        /// </summary>
        internal static string DevCard_BoughtThisTurn {
            get {
                return ResourceManager.GetString("DevCard_BoughtThisTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any of that kind of card to play!.
        /// </summary>
        internal static string DevCard_NoCard {
            get {
                return ResourceManager.GetString("DevCard_NoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the hex of the type of resource you would like to trade away.
        /// </summary>
        internal static string DoTrade_Instruction {
            get {
                return ResourceManager.GetString("DoTrade_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, you don&apos;t have enough of that to trade. Select the hex of the type of resource you would like to trade away..
        /// </summary>
        internal static string DoTrade_NotEnough {
            get {
                return ResourceManager.GetString("DoTrade_NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select the hex of the a different resource type you would like to receive.
        /// </summary>
        internal static string DoTrade_SelectWant {
            get {
                return ResourceManager.GetString("DoTrade_SelectWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brick.
        /// </summary>
        internal static string Item_Brick {
            get {
                return ResourceManager.GetString("Item_Brick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Item_City {
            get {
                return ResourceManager.GetString("Item_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desert.
        /// </summary>
        internal static string Item_Desert {
            get {
                return ResourceManager.GetString("Item_Desert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grain.
        /// </summary>
        internal static string Item_Grain {
            get {
                return ResourceManager.GetString("Item_Grain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knight Card.
        /// </summary>
        internal static string Item_KnightCard {
            get {
                return ResourceManager.GetString("Item_KnightCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest Army Owner:.
        /// </summary>
        internal static string Item_LargestArmyCard {
            get {
                return ResourceManager.GetString("Item_LargestArmyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longest Road Owner:.
        /// </summary>
        internal static string Item_LongestRoadCard {
            get {
                return ResourceManager.GetString("Item_LongestRoadCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lumber.
        /// </summary>
        internal static string Item_Lumber {
            get {
                return ResourceManager.GetString("Item_Lumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monopoly Card.
        /// </summary>
        internal static string Item_MonopolyCard {
            get {
                return ResourceManager.GetString("Item_MonopolyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore.
        /// </summary>
        internal static string Item_Ore {
            get {
                return ResourceManager.GetString("Item_Ore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        internal static string Item_Road {
            get {
                return ResourceManager.GetString("Item_Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Building Card.
        /// </summary>
        internal static string Item_RoadBuildingCard {
            get {
                return ResourceManager.GetString("Item_RoadBuildingCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settlement.
        /// </summary>
        internal static string Item_Settlement {
            get {
                return ResourceManager.GetString("Item_Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory Point Card.
        /// </summary>
        internal static string Item_VictoryPointCard {
            get {
                return ResourceManager.GetString("Item_VictoryPointCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wool.
        /// </summary>
        internal static string Item_Wool {
            get {
                return ResourceManager.GetString("Item_Wool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Plenty Card.
        /// </summary>
        internal static string Item_YearOfPlentyCard {
            get {
                return ResourceManager.GetString("Item_YearOfPlentyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a hex to place the Robber on..
        /// </summary>
        internal static string MoveRobber_Instruction {
            get {
                return ResourceManager.GetString("MoveRobber_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a DIFFERENT hex to place the Robber on..
        /// </summary>
        internal static string MoveRobber_SameHexNotAllowed {
            get {
                return ResourceManager.GetString("MoveRobber_SameHexNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a city you own to upgrade..
        /// </summary>
        internal static string PlaceCity_Failed {
            get {
                return ResourceManager.GetString("PlaceCity_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place a city..
        /// </summary>
        internal static string PlaceCity_Instruction {
            get {
                return ResourceManager.GetString("PlaceCity_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place a road next to that settlement..
        /// </summary>
        internal static string PlaceInitialRoad_Instruction {
            get {
                return ResourceManager.GetString("PlaceInitialRoad_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your road must be placed next to your new settlement..
        /// </summary>
        internal static string PlaceInitialRoad_NotAdjacent {
            get {
                return ResourceManager.GetString("PlaceInitialRoad_NotAdjacent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your settlement must be at least two roads away from other settlements..
        /// </summary>
        internal static string PlaceInitialSettlement_InvalidLocation {
            get {
                return ResourceManager.GetString("PlaceInitialSettlement_InvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settlements must be placed on intersections..
        /// </summary>
        internal static string PlaceInitialSettlement_NotIntersection {
            get {
                return ResourceManager.GetString("PlaceInitialSettlement_NotIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot place a road there because is already occupied..
        /// </summary>
        internal static string PlaceRoad_AlreadyOccupied {
            get {
                return ResourceManager.GetString("PlaceRoad_AlreadyOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your road must be adjacent to one of your cities, settlements, or roads, and cannot cross other player&apos;s settlements or cities..
        /// </summary>
        internal static string PlaceRoad_Failed {
            get {
                return ResourceManager.GetString("PlaceRoad_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place a road..
        /// </summary>
        internal static string PlaceRoad_Instruction {
            get {
                return ResourceManager.GetString("PlaceRoad_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a path!.
        /// </summary>
        internal static string PlaceRoad_NotPath {
            get {
                return ResourceManager.GetString("PlaceRoad_NotPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settlement must be placed next to a road you own, at least two roads away from another settlement..
        /// </summary>
        internal static string PlaceSettlement_Fail {
            get {
                return ResourceManager.GetString("PlaceSettlement_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place a settlement..
        /// </summary>
        internal static string PlaceSettlement_Instruction {
            get {
                return ResourceManager.GetString("PlaceSettlement_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Player_None {
            get {
                return ResourceManager.GetString("Player_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Player_PlayerColor_Blue {
            get {
                return ResourceManager.GetString("Player_PlayerColor_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Player_PlayerColor_Orange {
            get {
                return ResourceManager.GetString("Player_PlayerColor_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Player_PlayerColor_Red {
            get {
                return ResourceManager.GetString("Player_PlayerColor_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string Player_PlayerColor_White {
            get {
                return ResourceManager.GetString("Player_PlayerColor_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have received the Largest Army Card..
        /// </summary>
        internal static string PlayKnightCard_ReceivedLargestArmy {
            get {
                return ResourceManager.GetString("PlayKnightCard_ReceivedLargestArmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a hex for the resource you would like to steal from everyone..
        /// </summary>
        internal static string PlayMonopoly_Instruction {
            get {
                return ResourceManager.GetString("PlayMonopoly_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re out of roads!.
        /// </summary>
        internal static string PlayRoadBuilding_NoRoads {
            get {
                return ResourceManager.GetString("PlayRoadBuilding_NoRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place the second road..
        /// </summary>
        internal static string PlayRoadBuilding_SecondInstruction {
            get {
                return ResourceManager.GetString("PlayRoadBuilding_SecondInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a hex for the first resource you would like to receive..
        /// </summary>
        internal static string PlayYearOfPlenty_Instruction {
            get {
                return ResourceManager.GetString("PlayYearOfPlenty_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a hex corresponding to the resource you wish to receive (Desert doesn&apos;t count!)..
        /// </summary>
        internal static string PlayYearOfPlenty_Invalid {
            get {
                return ResourceManager.GetString("PlayYearOfPlenty_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, there are no remaining resources..
        /// </summary>
        internal static string PlayYearOfPlenty_OutOfAllResources {
            get {
                return ResourceManager.GetString("PlayYearOfPlenty_OutOfAllResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, that resource has run out. Select a different hex for a resource you would like to receive..
        /// </summary>
        internal static string PlayYearOfPlenty_OutOfAResource {
            get {
                return ResourceManager.GetString("PlayYearOfPlenty_OutOfAResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a hex for the second resource you would like to receive..
        /// </summary>
        internal static string PlayYearOfPlenty_SecondInstruction {
            get {
                return ResourceManager.GetString("PlayYearOfPlenty_SecondInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Wins!.
        /// </summary>
        internal static string Presenter_DisplayPlayerVictory_VictoryTextFormat {
            get {
                return ResourceManager.GetString("Presenter_DisplayPlayerVictory_VictoryTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string Presenter_KeyValueFormat {
            get {
                return ResourceManager.GetString("Presenter_KeyValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        internal static string Presenter_PromptUser_UserMessageFormat {
            get {
                return ResourceManager.GetString("Presenter_PromptUser_UserMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stealing from yourself is not a valid choice! Select an adjacent city or settlement!.
        /// </summary>
        internal static string Rob_CannotRobSelf {
            get {
                return ResourceManager.GetString("Rob_CannotRobSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select an adjacent city or settlement to steal a resource from..
        /// </summary>
        internal static string Rob_Instruction {
            get {
                return ResourceManager.GetString("Rob_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to that city is not adjacent! Select an adjacent city or settlement!.
        /// </summary>
        internal static string Rob_MustBeAdjacent {
            get {
                return ResourceManager.GetString("Rob_MustBeAdjacent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no city or settlement there! Select an adjacent city or settlement!.
        /// </summary>
        internal static string Rob_MustSelectCity {
            get {
                return ResourceManager.GetString("Rob_MustSelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what a pity! that player didn&apos;t have any resources..
        /// </summary>
        internal static string Rob_PlayerIsBroke {
            get {
                return ResourceManager.GetString("Rob_PlayerIsBroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roll dice..
        /// </summary>
        internal static string RollDice_Instruction {
            get {
                return ResourceManager.GetString("RollDice_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start!.
        /// </summary>
        internal static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlers of Catan.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, the bank is out of resources. Move to build phase..
        /// </summary>
        internal static string Trade_BankCantTrade {
            get {
                return ResourceManager.GetString("Trade_BankCantTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select harbor or 4:1 to trade or move to build phase.
        /// </summary>
        internal static string Trade_Instruction {
            get {
                return ResourceManager.GetString("Trade_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t have a settlement or city next to that harbor..
        /// </summary>
        internal static string Trade_InvalidHarbor {
            get {
                return ResourceManager.GetString("Trade_InvalidHarbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry, you don&apos;t have enough resources to trade that way..
        /// </summary>
        internal static string Trade_NotEnoughToTrade {
            get {
                return ResourceManager.GetString("Trade_NotEnoughToTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected an invalid action or target for an action. Please try again..
        /// </summary>
        internal static string TurnState_GeneralInvalidInput {
            get {
                return ResourceManager.GetString("TurnState_GeneralInvalidInput", resourceCulture);
            }
        }
    }
}
